/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Cloud/Cloud2.glb -o src/components/Cloud/Cloud2.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud2(props) {
  const { nodes, materials } = useGLTF('/models/Cloud/Cloud2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/models/Cloud/Cloud2.glb')
