/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Boards/Billboard.glb -o src/components/Boards/Billboard.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Billboard(props) {
  const { nodes, materials } = useGLTF('/models/Boards/Billboard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.c.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.a.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.b.geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('/models/Boards/Billboard.glb')
