/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Boards/WoodenSignWithChain.glb -o src/components/Animals/WoodenSignWithChain.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WoodenSignWithChain(props) {
  const { nodes, materials } = useGLTF('/models/Boards/WoodenSignWithChain.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh geometry={nodes.Sign4_1.geometry} material={materials['Dark Wood']} />
        <mesh geometry={nodes.Sign4_2.geometry} material={materials['Light Wood']} />
        <mesh geometry={nodes.Sign4_3.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.Sign4_4.geometry} material={materials.Herbs} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Boards/WoodenSignWithChain.glb')
