/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Boards/WoodenSign.glb -o src/components/Boards/WoodenSign.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WoodenSign(props) {
  const { nodes, materials } = useGLTF('/models/Boards/WoodenSign.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh geometry={nodes.Sign8_1.geometry} material={materials['Dark Wood']} />
        <mesh geometry={nodes.Sign8_2.geometry} material={materials['Light Wood']} />
        <mesh geometry={nodes.Sign8_3.geometry} material={materials.Herbs} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Boards/WoodenSign.glb')
